export type SelectAntdType = {
    label: string,
    value: string
}

export const BankSelectionData: SelectAntdType[] = [
    { label: "Không chọn", value: "" },
    { label: "Thanh toán QRONLY", value: "QRONLY" },
    { label: "Ứng dụng MobileBanking", value: "MBAPP" },
    { label: "VNPAYQR", value: "VNPAYQR" },
    { label: "LOCAL BANK", value: "VNBANK" },
    { label: "INTERNET BANKING", value: "IB" },
    { label: "ATM CARD", value: "ATM" },
    { label: "INTERNATIONAL CARD", value: "INTCARD" },
    { label: "VISA", value: "VISA" },
    { label: "MASTERCARD", value: "MASTERCARD" },
    { label: "JCB", value: "JCB" },
    { label: "UPI", value: "UPI" },
    { label: "VIB", value: "VIB" },
    { label: "VIETCAPITALBANK", value: "VIETCAPITALBANK" },
    { label: "Ngân hàng SCB", value: "SCB" },
    { label: "Ngân hàng NCB", value: "NCB" },
    { label: "Ngân hàng SacomBank", value: "SACOMBANK" },
    { label: "Ngân hàng EximBank", value: "EXIMBANK" },
    { label: "Ngân hàng MSBANK", value: "MSBANK" },
    { label: "Ngân hàng NamABank", value: "NAMABANK" },
    { label: "Ví điện tử VnMart", value: "VNMART" },
    { label: "Ngân hàng Vietinbank", value: "VIETINBANK" },
    { label: "Ngân hàng VCB", value: "VIETCOMBANK" },
    { label: "Ngân hàng HDBank", value: "HDBANK" },
    { label: "Ngân hàng Đông Á", value: "DONGABANK" },
    { label: "Ngân hàng TPBank", value: "TPBANK" },
    { label: "Ngân hàng OceanBank", value: "OJB" },
    { label: "Ngân hàng BIDV", value: "BIDV" },
    { label: "Ngân hàng Techcombank", value: "TECHCOMBANK" },
    { label: "Ngân hàng VPBank", value: "VPBANK" },
    { label: "Ngân hàng Agribank", value: "AGRIBANK" },
    { label: "Ngân hàng MBBank", value: "MBBANK" },
    { label: "Ngân hàng ACB", value: "ACB" },
    { label: "Ngân hàng OCB", value: "OCB" },
    { label: "Ngân hàng IVB", value: "IVB" },
    { label: "Ngân hàng SHB", value: "SHB" },
    { label: "Apple Pay", value: "APPLEPAY" },
    { label: "Google Pay", value: "GOOGLEPAY" }
];